### ISSUE TITLE
`Field<T>` should optionally allow passing an SQL column name, like `Field<T, Name>`

### ISSUE THREAD

**Issue by christianparpart** [LASTRADA-Software/Lightweight#136]
We currently infer the SQL column name by compile-time reflecting the variable name of the given field.

This is good, but sometimes on already existing databases, the table and column names are not nicely chosen and that would make it hard to read on the C++ side (or inconvenient).

The idea is to allow passing an SQL name override as template parameter, e.g. like so:

```cpp
struct Person
{
    Field<uint64_t, "NR"> id;          // SQL column name is "NR"
    Field<SqlString<30>, "NAME"> name; // SQL column name is "NAME"
    Field<SqlString<40>> email;         // SQL column name is "email", as inferred by the member name
};
```

**Comment by christianparpart** [comment]
@FelixTheC does this make sense to you?

**Comment by FelixTheC** [comment]
@christianparpart looks good I really had something like this in my mind
https://docs.pydantic.dev/latest/concepts/alias/

**Comment by christianparpart** [comment]
> @christianparpart looks good I really had something like this in my mind https://docs.pydantic.dev/latest/concepts/alias/

It should actually be also possible like so:

```cpp
Field<int, SqlColumnAlias<"BLAH">> field;
```
